build:
  version: "3.0"

product-service:
  message: "product-service related dev APIs - updated"
  contactDetails:
    name: "Carol"
    email: "carol@easycar.com"
  onCallSupport:
    - (111) 222-7777
    - (111) 222-8888
