build:
  version: "2.0"

product-service:
  message: "product-service related qa APIs "
  contactDetails:
    name: "Bob"
    email: "bob@easycar.com"
  onCallSupport:
    - (111) 222-5555
    - (111) 222-6666